apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cost-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cost-backend
  template:
    metadata:
      labels:
        app: aws-cost-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 8000
