apiVersion: v1
kind: Service
metadata:
  name: aws-cost-backend
  labels:
    app: aws-cost-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: aws-cost-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.backend.service.nodePort }}
