apiVersion: v1
kind: Service
metadata:
  name: aws-cost-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: aws-cost-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      nodePort: {{ .Values.frontend.service.nodePort }}
