name: CI Pipeline - AWS Cost Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------
      # Backend Service
      # -----------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: Run backend tests (placeholder)
        working-directory: backend
        run: |
          echo "Run backend tests here"

      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aws-cost-backend:latest backend/

      # -----------------------
      # Frontend Service
      # -----------------------
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aws-cost-frontend:latest frontend/

      # -----------------------
      # Docker Login
      # -----------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -----------------------
      # Push Images
      # -----------------------
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aws-cost-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aws-cost-frontend:latest
